services:
  mysql-test:
    image: "mysql:latest"
    container_name: "test-mysql"
    ports:
      - "3307:3307"
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "coxwave"
      MYSQL_TCP_PORT: 3307
